### ISSUE TITLE
Doc - Readme File is empty

### ISSUE THREAD

**Issue by cgbosse** [Nautilus-Cyberneering/chinese-ideographs#1]
We need to expand and improve information of the file starting by the project description.

- [x] Create a content list
- [x] Include Ethical Software collaboration remark
- [x] Include Ethical Software content license and policy link.
- [x] Include Roadmap

**Comment by josecelano** [comment]
@cgbosse can we close this issue? I think you added the roadmap and I do not know what you mean by "Create a content list".
