### ISSUE TITLE
Define - Pull request process (branches)

### ISSUE THREAD

**Issue by cgbosse** [Nautilus-Cyberneering/chinese-ideographs#27]

**Comment by josecelano** [comment]
I have explained the process from the development point of view: https://github.com/Nautilus-Cyberneering/chinese-ideographs/pull/37/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R112-R118

and we also explained it from the artist's point of view: https://github.com/Nautilus-Cyberneering/chinese-ideographs/blob/main/documentation/Gold_Images.md#adding-a-new-gold-image

Adding a new image is a concrete type of pull request. We should at least link both files or improve the second explaining how to create the pull request and title/description/commit conventions.
