### ISSUE TITLE
Add image operations to base image processing pipeline

### ISSUE THREAD

**Issue by yeraydavidrodriguez** [Nautilus-Cyberneering/chinese-ideographs#89]
The image processing actions that have been created must be linked together to form a base image processing pipeline.

The relevant actions to be used are:

- Image resize (#41 )
- Image ICC profile modification (#57 )
- Image file format change (#87 )
- Move file to the folder in which base image is to be stored (#90 )

The first action (image resize) must receive the output of the DVC DIFF action. Each action will add "input" and "output" file lists to this structure.

**Comment by josecelano** [comment]
@yeraydavidrodriguez I'm going to merge this PR and continue working with the issue https://github.com/Nautilus-Cyberneering/chinese-ideographs/issues/70. The Base image is generated, we only need to add the image to DVC storage and create a commit for the image tiff and the dvc files (.dvc extension)

**Comment by yeraydavidrodriguez** [comment]
Fine for me, @josecelano , please proceed.
